import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

import ReduxProvider from "@/components/provider/redux-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <head>
          <title>Video Embed App</title>
        </head>
        <body>
          <ReduxProvider>
            {children}
            <Toaster />
          </ReduxProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
